### ISSUE TITLE
Question regarding the pretrained latent_vgg.ckpt

### ISSUE THREAD

**Issue by alchan00** [GunwooHan/E-LatentLPIPS#2]
Hello, can you elucidate how the posted ckpt was trained?
Is it trained with imagenet in latent space, and then linearly tuned with BAPPS?
Or maybe one of the two has been skipped?

**Comment by GunwooHan** [comment]
Hi. I reproduced it based on VGG, and basically used the imagenet pretrained model
The checkpoint file is only linear tuned with BAPPS using pytorch pretrained VGG
